version: "3.8"
services:

  namenode:
    container_name: namenode
    build:
      context: .
      dockerfile: namenode.dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - db
  storage:
    container_name: storage
    build:
      context: .
      dockerfile: storage_node.dockerfile
    depends_on:
      - namenode
  db:
    container_name: db
    build: postgres
