version: "3.8"
services:

  namenode:
    container_name: namenode
    restart: on-failure
    environment:
      DB_ADDR: 127.0.0.1
      DB_LOGIN: nikitasmirnov
      DB_PASS: yanikitasmirnov
      DB_NAME: test
      DEBUG: 1
    build:
      context: .
      dockerfile: namenode.dockerfile
#    ports:
#      - "8000:8000"
    depends_on:
      - db
    network_mode: "host"
  storage:
    container_name: storage
    environment:
      NAMENODE_ADDR: http://127.0.0.1:8000
      WORKING_DIR: /var/storage
      DB_ADDR: 127.0.0.1
      DB_LOGIN: nikitasmirnov
      DB_PASS: yanikitasmirnov
      DB_NAME: test
      DEBUG: 1
    build:
      context: .
      dockerfile: storage_node.dockerfile
    volumes:
    - /var/storage:/var/storage
    depends_on:
      - namenode
#    ports:
#      - "8001:8001"
    restart: on-failure
    network_mode: "host"
  db:
    container_name: db
    environment:
      POSTGRES_USER: nikitasmirnov
      POSTGRES_PASSWORD: yanikitasmirnov
      POSTGRES_DB: test
    build: postgres
    volumes:
      - type: bind
        source: ./postgres/pg_hba.conf
        target: /var/lib/postgresql/data/pg_hba.conf
#    ports:
#      - "5432:5432"
    network_mode: "host"
