version: "3.8"
services:

  storage:
    container_name: storage
    env_file:
      - ./storage.env
    build:
      context: .
      dockerfile: storage_node.dockerfile
    volumes:
    - /var/storage:/var/storage
    restart: on-failure
    network_mode: "host"